'use strict';

/**
 * Emits the Code-node source for the card renderer webhook.
 *
 * The card page has to be served as real text/html for a screenshot service to
 * render it. GitHub file CDNs will not do that — githack shows a click-through
 * interstitial and statically.io serves the source as plain text, both of which
 * screenshot as a page that is not the card. So n8n serves it itself.
 *
 * Fonts are referenced from the repo rather than embedded, pinned to a commit,
 * to keep the node a few kB instead of a few hundred.
 *
 *   node render/build-webhook.js [sha] > out.js
 *
 * Paste the result into the "Build Card Page" node of the renderer workflow.
 */

const { execSync } = require('child_process');
const { buildShell } = require('./template');

const sha = process.argv[2] || execSync('git rev-parse HEAD', { cwd: __dirname }).toString().trim();
const fontBase = 'https://raw.githubusercontent.com/Malek-Abdelrahman918/LinkedIn-/' + sha + '/render/fonts';

const html = buildShell({ fontBase });

process.stdout.write(
  '// The card page, served as HTML. Generated by render/build-webhook.js from\n' +
  '// render/template.js. Edit there and regenerate; do not hand-edit this node.\n' +
  '// Fonts pinned to ' + sha + '\n' +
  'const html = ' + JSON.stringify(html) + ';\n\n' +
  'return [{ json: { html: html } }];\n'
);
